n = int(input('Digite o numero que deseja ver a tabuada: '))
print('''{} x 1 = {}
{} x 2 = {}
{} X 3 = {}
{} X 4 = {}
{} X 5 = {}
{} X 6 = {}
{} X 7 = {}
{} X 8 = {}
{} X 9 = {}
{} X 10 = {}'''.format(n,n*1,n,n*2,n,n*3,n,n*4,n,n*5,n,n*6,n,n*7,n,n*8,n,n*9,n,n*10))
